import os

class LLMService:
    def __init__(self, api_key=None):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        # In a real scenario, initialize OpenAI client here
        
    def generate_explanation(self, prompt: str) -> str:
        """
        Generate an explanation based on the prompt.
        If API key is present, calls LLM.
        Otherwise, uses a fallback template based on parsing the input.
        """
        if self.api_key:
            return self._call_llm(prompt)
        else:
            return self._simulate_llm(prompt)
            
    def _call_llm(self, prompt: str) -> str:
        # Placeholder for actual API call
        # form: client.chat.completions.create(...)
        return "Explanation generated by AI (API mode)..."

    SKILL_MAPPING = {
        'T_Kiểu_dữ_liệu_Viết_vòng_lặp_Viết_hàm': ['Sử dụng vòng lặp', 'Khai báo biến cơ bản', 'Viết hàm tái sử dụng'],
        'T_Số_học': ['Tư duy toán học', 'Xử lý tính toán số học'],
        'T_Mảng_một_chiều': ['Duyệt mảng', 'Truy xuất phần tử', 'Thao tác dữ liệu tuyến tính'],
        'T_Mảng_hai_chiều': ['Xử lý ma trận', 'Duyệt mảng đa chiều'],
        'T_Kiểu_dữ_liệu_string_và_áp_dụng': ['Xử lý chuỗi ký tự', 'Thao tác văn bản', 'Phân tích cú pháp'],
        'T_Sắp_xếp': ['Tối ưu hóa sắp xếp', 'So sánh phần tử'],
        'T_Tìm_kiếm': ['Kỹ năng tìm kiếm nhị phân/tuyến tính', 'Tối ưu truy vấn'],
        'T_Cấu_trúc_cơ_bản': ['Tổ chức dữ liệu struct'],
        'L_1': ['Kỹ năng nhận biết cơ bản'],
        'L_2': ['Kỹ năng vận dụng đơn giản'],
        'L_3': ['Kỹ năng vận dụng nâng cao'],
        'L_4': ['Tư duy phân tích phức tạp'],
        'L_5': ['Tư duy sáng tạo và tối ưu']
    }

    def _simulate_llm(self, prompt: str) -> str:
        """
        Smart fallback that parses the detailed prompt to reconstruct a natural response.
        """
        try:
            # Extract key info from the structured prompt
            lines = prompt.split('\n')
            item_id = ""
            paths = []
            current_path = None
            
            for line in lines:
                line = line.strip()
                if line.startswith('item_id ='):
                    item_id = line.split('=')[1].strip().strip('"')
                elif line.startswith('Path'):
                    if current_path: paths.append(current_path)
                    current_path = {'score': 0, 'steps': []}
                    if 'attention:' in line:
                        try:
                            score_str = line.split('attention:')[1].split(')')[0].strip()
                            current_path['score'] = float(score_str)
                        except: pass
                elif '--[' in line and current_path is not None:
                    parts = line.split('--[')
                    head = parts[0].strip()
                    rest = parts[1].split(']-->')
                    relation = rest[0].strip()
                    tail_part = rest[1].split('(attention:')[0].strip()
                    current_path['steps'].append({'head': head, 'relation': relation, 'tail': tail_part})

            if current_path: paths.append(current_path)
            
            if not paths:
                return f"Hệ thống gợi ý bài tập **{item_id}** dựa trên phân tích lộ trình học tập của bạn."

            # Construct Reasoning
            best_path = paths[0]
            steps = best_path['steps']
            
            reasoning = []
            
            # Header
            reasoning.append(f"Mô hình EduKGAT phát hiện mối liên kết học tập giữa bài mới và lịch sử của bạn.")
            
            if len(steps) >= 2:
                history_item = steps[0]['head']
                middle_node = steps[0]['tail']
                
                # 1. Context (Mental Anchor)
                skills = self.SKILL_MAPPING.get(middle_node, [f"Kiến thức về {middle_node.replace('T_', '').replace('_', ' ')}"])
                skill_bullets = "\n".join([f"- {s}" for s in skills])
                
                reasoning.append(f"\nSau khi làm bài **{history_item}**, bạn đã bước đầu tiếp cận:\n{skill_bullets}")
                
                # 2. Proposition (New Value)
                reasoning.append(f"\nBài **{item_id}** tiếp tục khai thác các kỹ năng này trong ngữ cảnh mới:")
                
                # Infer new context based on target item name keywords
                target_context = []
                name_lower = item_id.lower()
                if "xâu" in name_lower or "chuỗi" in name_lower:
                    target_context.append("Áp dụng kỹ năng vào xử lý văn bản/chuỗi ký tự")
                if "số" in name_lower or "tính" in name_lower:
                    target_context.append("Rèn luyện tư duy tính toán số học chuẩn xác")
                if "mảng" in name_lower or "trận" in name_lower:
                    target_context.append("Tăng cường khả năng thao tác với dữ liệu có cấu trúc")
                if "sắp xếp" in name_lower:
                    target_context.append("Hiểu sâu về thứ tự và tối ưu hóa vị trí")
                
                # Default context if none found
                if not target_context:
                    target_context.append(f"Vận dụng kiến thức {middle_node.replace('T_', '').replace('_', ' ')} vào bài toán thực tế")
                    
                target_bullets = "\n".join([f"- {t}" for t in target_context])
                reasoning.append(target_bullets)
                
                # 3. Conclusion (Benefit)
                reasoning.append(f"\nViệc chuyển đổi ngữ cảnh này giúp bạn **mở rộng khả năng lập trình** mà không làm tăng độ khó đột ngột.")
                
            else:
                reasoning.append(f"\nGợi ý này dựa trên sự tương đồng trực tiếp với các bài tập bạn đã làm tốt gần đây, giúp củng cố kiến thức nền tảng.")

            return "\n".join(reasoning)

        except Exception as e:
            print(f"Error simulating LLM: {e}")
            import traceback
            traceback.print_exc()
            return f"Bài tập **{item_id}** được gợi ý để tối ưu hóa lộ trình của bạn."

        except Exception as e:
            print(f"Error simulating LLM: {e}")
            return f"Bài tập **{item_id}** được gợi ý dựa trên phân tích đồ thị tri thức và lịch sử học tập của bạn, nhằm tối ưu hóa lộ trình phát triển năng lực."

def get_llm_service():
    return LLMService()
